# Etapa de build
FROM maven:3.9.7-amazoncorretto-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa final - apenas o JAR pronto
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/email-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
